### ISSUE TITLE
No connection, no error, in Unity

### ISSUE THREAD

**Issue by adamsingle** [TwitchLib/TwitchLib.Unity#40]
I'm picking up a project I started quite a while ago in which I had my twitch connection working. For some reason it no longer is. I've updated my dll to the latest. I get no connection happening. There are no errors or warnings. I have been through the guide, redone every step, but no connection is made and nothing is failing. The guide says to check my code, which I've done many times over now. Are there any known issues that would cause this? Any help would be appreciated

**Comment by RRickkert** [comment]
See #36

**Comment by RRickkert** [comment]
@swiftyspiffy I believe this issue can be closed.

**Comment by swiftyspiffy** [comment]
Will do, thanks @RRickkert
