### ISSUE TITLE
IRC Commands

### ISSUE THREAD

**Issue by uurha** [TwitchLib/TwitchLib.Unity#56]
Hi, I meet the problem that not possible to send "/vips" message. Someone have suggestion?

**Comment by swiftyspiffy** [comment]
You can probably use:
```
client.SendRaw("/vips");
```

**Comment by swiftyspiffy** [comment]
Er wait, that's a chat command.

Just use:
```
client.SendMessage("channel", "/vips");
```

**Comment by uurha** [comment]
> Er wait, that's a chat command.
> 
> Just use:
> 
> ```
> client.SendMessage("channel", "/vips");
> ```

Sorry but not working. Also tried " client.SendRaw("/vips"); " (this not totally correct (correct syntax client.SendRaw("<user>!<user>@<user>.tmi.twitch.tv PRIVMSG #<channel> :/vips"); )) but it's not working.

**Comment by uurha** [comment]
I think that problem because released dll is obsolete.

**Comment by swiftyspiffy** [comment]
Try using the dot notation:
```
client.SendMessage("channel", ".vips");
```

Also is it possible the channel doesn't have VIPs enabled or doesn't have any?

**Comment by uurha** [comment]
> Try using the dot notation:
> 
> ```
> client.SendMessage("channel", ".vips");
> ```
> 
> Also is it possible the channel doesn't have VIPs enabled or doesn't have any?

okay, I'll try. Channel have vips and chat:read enabled for bot

**Comment by uurha** [comment]
No still not working (I just update plugin to 1.0.1)

**Comment by uurha** [comment]
omfg, I found out that answer for .vips you receiving in OnVIPsReceived event (in 1.0,1 version). Thx for your patience.

**Comment by swiftyspiffy** [comment]
Ya... totally forgot about that. Sorry :(
